import React from "react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<React.Fragment>
    <div>홈헤더</div>
    {children}
  </React.Fragment>
  )
}
